### ISSUE TITLE
Unexpected Failure: PathNotFoundException di produk bundling muncul ketika menghapus produk bundling

### ISSUE THREAD

**Issue by chysiaa** [hansenbudinata21/ligomitra-public-issue-tracker#10]

**Comment by hansenbudinata21** [comment]
cause utama: data bundle bisa di hapus di FE, tetapi di BE ada validasi yang salah sehingga data gagal dihapus
fixed di versi terbaru
utk handling path not found, di issue: https://github.com/hansenbudinata21/ligomitra-public-issue-tracker/issues/1
