### ISSUE TITLE
Saat edit produk dengan varian produk on, tidak bisa menambahkan varian produk dan muncul form satuan, add on dan bahan

### ISSUE THREAD

**Issue by chysiaa** [hansenbudinata21/ligomitra-public-issue-tracker#5]

**Comment by hansenbudinata21** [comment]
udah tau penyebab nya, tapi blm bisa reproduce supaya bug nya kejadian lg
minta bantu record step2 reproduce nya dong

**Comment by hansenbudinata21** [comment]
root cause found: ketika save data yang kosong, skunumber/satuan default nya beda antara FE dan db ("-" vs "")
