### ISSUE TITLE
Pada kalender, tidak ada icon untuk memilih tahun atau bulan. Fungsionalnya ada tapi perlu di klik di blank space atas kiri

### ISSUE THREAD

**Issue by chysiaa** [hansenbudinata21/ligomitra-public-issue-tracker#8]

**Comment by hansenbudinata21** [comment]
added di versi terbaru
sementara ditambahkan:
- arrow utk navigasi antar bulan
- nama bulan tetap bisa diclick utk switch view antara months <-> years <-> decades <-> centuries
- swipe listener di body calender utk navigasi antar bulan (alternative dari arrow)

better ux tbd later
